version: '3.9'
services:
  api:
    build: ./api
    ports:
      - "3001:3001"

  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3001

  admin:
    build: ./admin
    ports:
      - "3002:3002"
